from django.core.management.base import BaseCommand
from shop.models import Category, Product


CATEGORIES = [
    ('turniki', 'Турники', '🏃', 1),
    ('brusya', 'Брусья', '💪', 2),
    ('shvedskie-stenki', 'Шведские стенки', '🧗', 3),
    ('dsk-atlet', 'ДСК Атлет', '🏅', 4),
    ('dsk-napolnye', 'ДСК напольные', '🏠', 5),
    ('dsk-formula', 'ДСК ФормулаЗдоровья', '🌿', 6),
    ('giperekstenzii', 'Гиперэкстензии', '🔄', 7),
    ('begovye-dorozhki', 'Беговые дорожки', '🏃', 8),
    ('boks-borba', 'Бокс и борьба', '🥊', 9),
    ('sportivnye-kompleksy', 'Спортивные комплексы', '🏟️', 10),
    ('skami', 'Скамьи для жима', '🏋️', 11),
    ('medboly', 'Медболы', '⚽', 12),
    ('inversionnye-stoly', 'Инверсионные столы', '🔃', 13),
    ('stoyki', 'Стойки силовые', '🔩', 14),
    ('dopolnitelnoe', 'Доп. оборудование', '🎯', 15),
]


PRODUCTS = [
    {
        'category_slug': 'begovye-dorozhki',
        'name':        'DFC JS-3643',
        'slug':        'product-199',
        'price':       53000,
        'image':       'images/products/H_199.jpg',
        'description': 'Характеристики DFC JS-3643',
        'is_hit': False,
        'order': 1,
    },
    {
        'category_slug': 'begovye-dorozhki',
        'name':        'DFC M100',
        'slug':        'product-200',
        'price':       32500,
        'image':       'images/products/H_200.jpg',
        'description': 'беговая дорожка DFC M100',
        'is_hit': False,
        'order': 2,
    },
    {
        'category_slug': 'begovye-dorozhki',
        'name':        'Proteus Larsen TM8420A',
        'slug':        'product-201',
        'price':       38500,
        'image':       'images/products/H_201.jpg',
        'description': 'Максимальный вес пользователя, кг: 120 Вес в собранном виде: 56 Размеры полотна, см: 42х126 Встроенный лоток: + Складная рама: + Ключ безопасности: + Скорость, км/ч: 1-16 Угол наклона полотна: 3 уровня , устанавливаются вручную Система измерения HP: Измерение пульса при помощи металлических датчиков',
        'is_hit': False,
        'order': 3,
    },
    {
        'category_slug': 'begovye-dorozhki',
        'name':        'DIADORA Edge 1.6 Dark',
        'slug':        'product-202',
        'price':       47500,
        'image':       'images/products/H_202.jpg',
        'description': '',
        'is_hit': False,
        'order': 4,
    },
    {
        'category_slug': 'begovye-dorozhki',
        'name':        'DFC T-420 LEGA',
        'slug':        'product-203',
        'price':       43500,
        'image':       'images/products/H_203.jpg',
        'description': 'Беговая дорожка DFC T-420 LEGA',
        'is_hit': False,
        'order': 5,
    },
    {
        'category_slug': 'begovye-dorozhki',
        'name':        'DFC Strong C4',
        'slug':        'product-204',
        'price':       41000,
        'image':       'images/products/H_204.jpg',
        'description': '',
        'is_hit': False,
        'order': 6,
    },
    {
        'category_slug': 'begovye-dorozhki',
        'name':        'CARBON T406',
        'slug':        'product-206',
        'price':       34500,
        'image':       'images/products/H_206.jpg',
        'description': '',
        'is_hit': True,
        'order': 7,
    },
    {
        'category_slug': 'begovye-dorozhki',
        'name':        'CARBON T556',
        'slug':        'product-209',
        'price':       45500,
        'image':       'images/products/H_209.jpg',
        'description': 'Тип электрическая Рама с однослойной покраской',
        'is_hit': False,
        'order': 8,
    },
    {
        'category_slug': 'begovye-dorozhki',
        'name':        'CARBON T606',
        'slug':        'product-210',
        'price':       48000,
        'image':       'images/products/H_210.jpg',
        'description': 'Тип электрическая Рама усиленная с однослойной покраской',
        'is_hit': False,
        'order': 9,
    },
    {
        'category_slug': 'begovye-dorozhki',
        'name':        'CARBON T651E',
        'slug':        'product-212',
        'price':       53500,
        'image':       'images/products/H_212.jpg',
        'description': 'Тип электрическая Рама усиленная с однослойной покраской',
        'is_hit': False,
        'order': 10,
    },
    {
        'category_slug': 'begovye-dorozhki',
        'name':        'CARBON T706 HRC',
        'slug':        'product-214',
        'price':       55000,
        'image':       'images/products/H_214.jpg',
        'description': 'Дорожка ориентирована на тех пользователей, которые предъявляют повышенные требования к тренировке. Двигатель 2.5 л.с., скорость до 16 км./ч., механический наклон, полотно 130*44 см., вес пользователя до 140 кг. и беспроводной приемник частоты пульса.',
        'is_hit': False,
        'order': 11,
    },
    {
        'category_slug': 'boks-borba',
        'name':        'Боксерский мешок 1',
        'slug':        'product-228',
        'price':       2500,
        'image':       'images/products/H_228.jpg',
        'description': '',
        'is_hit': False,
        'order': 1,
    },
    {
        'category_slug': 'boks-borba',
        'name':        'Боксерский мешок 2',
        'slug':        'product-229',
        'price':       2700,
        'image':       'images/products/H_229.jpg',
        'description': '',
        'is_hit': False,
        'order': 2,
    },
    {
        'category_slug': 'boks-borba',
        'name':        'Боксерский мешок 3',
        'slug':        'product-230',
        'price':       2900,
        'image':       'images/products/H_230.jpg',
        'description': '',
        'is_hit': False,
        'order': 3,
    },
    {
        'category_slug': 'boks-borba',
        'name':        'Боксерский мешок 4',
        'slug':        'product-231',
        'price':       3700,
        'image':       'images/products/H_231.jpg',
        'description': '',
        'is_hit': False,
        'order': 4,
    },
    {
        'category_slug': 'boks-borba',
        'name':        'Боксерский мешок 5',
        'slug':        'product-232',
        'price':       3900,
        'image':       'images/products/H_232.jpg',
        'description': '',
        'is_hit': False,
        'order': 5,
    },
    {
        'category_slug': 'boks-borba',
        'name':        'Боксерский мешок 6',
        'slug':        'product-233',
        'price':       4100,
        'image':       'images/products/H_233.jpg',
        'description': '',
        'is_hit': False,
        'order': 6,
    },
    {
        'category_slug': 'boks-borba',
        'name':        'Боксерский мешок 7',
        'slug':        'product-234',
        'price':       4800,
        'image':       'images/products/H_234.jpg',
        'description': '',
        'is_hit': True,
        'order': 7,
    },
    {
        'category_slug': 'boks-borba',
        'name':        'Боксерский мешок 8',
        'slug':        'product-235',
        'price':       6500,
        'image':       'images/products/H_235.jpg',
        'description': '',
        'is_hit': False,
        'order': 8,
    },
    {
        'category_slug': 'boks-borba',
        'name':        'Подушка настенная для бокса',
        'slug':        'product-236',
        'price':       5500,
        'image':       'images/products/H_236.jpg',
        'description': 'Настенная подушка для бокса -- это компактный и удобный в использовании снаряд, который подойдет даже для домашних тренировок.',
        'is_hit': False,
        'order': 9,
    },
    {
        'category_slug': 'boks-borba',
        'name':        'Чучело борцовское',
        'slug':        'product-237',
        'price':       6600,
        'image':       'images/products/H_237.jpg',
        'description': 'Борцовское чучело - специальный снаряд для отработки различных захватов, бросков, приемов.',
        'is_hit': False,
        'order': 10,
    },
    {
        'category_slug': 'boks-borba',
        'name':        'fightball',
        'slug':        'product-242',
        'price':       500,
        'image':       'images/products/H_242.jpg',
        'description': 'fight ball развивает скорость, точность и хлесткость удара! С "Боевым Мячом" могут заниматься как профессионалы так и новички! Универсальная замена пневмо-груши! Удобно пользоваться, легко брать с собой в поездки и командировки, чтобы везде оставаться в тонусе! С подобным тренажером занимаются Рой Д',
        'is_hit': False,
        'order': 11,
    },
    {
        'category_slug': 'boks-borba',
        'name':        'Ремешок для прокачки шеи',
        'slug':        'product-243',
        'price':       1500,
        'image':       'images/products/H_243.jpg',
        'description': 'Ремень для прокачки шеи',
        'is_hit': False,
        'order': 12,
    },
    {
        'category_slug': 'boks-borba',
        'name':        'Боксерский мешок детский',
        'slug':        'product-249',
        'price':       1500,
        'image':       'images/products/H_249.jpg',
        'description': '',
        'is_hit': False,
        'order': 13,
    },
    {
        'category_slug': 'boks-borba',
        'name':        'Форма груши',
        'slug':        'product-250',
        'price':       5500,
        'image':       'images/products/H_250.jpg',
        'description': 'Боксерский снаряд в форме груши весом 30 кг для совершенствования ударов бокса (прямые и боковые удары). Предназначен для развития точности и быстроты ударов. Подвешивается на уровне груди боксера. Материал - тент.',
        'is_hit': False,
        'order': 14,
    },
    {
        'category_slug': 'boks-borba',
        'name':        'Силуэт малый',
        'slug':        'product-251',
        'price':       6000,
        'image':       'images/products/H_251.jpg',
        'description': 'Мешок боксерский, фигурный, с подвесным принципом, весом 40-45 кг обладает удобной системой фиксации и предназначен для отработки жёсткости ударов руками (удобен для апперкота) и ногами. Материал - тент.',
        'is_hit': False,
        'order': 15,
    },
    {
        'category_slug': 'boks-borba',
        'name':        'Силуэт большой',
        'slug':        'product-252',
        'price':       8000,
        'image':       'images/products/H_252.jpg',
        'description': 'Мешок боксерский, фигурный, с подвесным принципом, весом 50-55 кг обладает удобной системой фиксации и предназначен для отработки жёсткости ударов руками (удобен для апперкота) и ногами (+low kick). Материал - тент.',
        'is_hit': False,
        'order': 16,
    },
    {
        'category_slug': 'brusya',
        'name':        'БРУСЬЯ ОТКИДНЫЕ СО СПИНКОЙ ДЛЯ ДСК СЕРИИ «ЮНЫЙ АТЛЕТ»',
        'slug':        'product-138',
        'price':       4000,
        'image':       'images/products/H_138.jpg',
        'description': 'Цветовое исполнение: красный, синий, зеленый, белый-антик-серебро. Допустимая нагрузка, кг: 120 Вес изделия, кг: 12',
        'is_hit': False,
        'order': 1,
    },
    {
        'category_slug': 'brusya',
        'name':        'Брусья навесные FFS',
        'slug':        'product-144',
        'price':       5000,
        'image':       'images/products/H_144.jpg',
        'description': '',
        'is_hit': False,
        'order': 2,
    },
    {
        'category_slug': 'brusya',
        'name':        'Брусья складные Шторм',
        'slug':        'product-163',
        'price':       5600,
        'image':       'images/products/H_163.jpg',
        'description': 'Эргономично расположены ручки для упражнениях на пресс, что позволяет не перенапрягать кисти.Благодаря складной конструкции, эти брусья можно установить в любом месте. Просто поднимите упоры вверх и брусья станут незаметными.',
        'is_hit': False,
        'order': 3,
    },
    {
        'category_slug': 'giperekstenzii',
        'name':        'Body-Solid GHYP-45',
        'slug':        'product-164',
        'price':       20000,
        'image':       'images/products/H_164.jpg',
        'description': '',
        'is_hit': False,
        'order': 1,
    },
    {
        'category_slug': 'giperekstenzii',
        'name':        'Гиперэкстензия «Эстетика»',
        'slug':        'product-165',
        'price':       11000,
        'image':       'images/products/H_165.jpg',
        'description': '',
        'is_hit': False,
        'order': 2,
    },
    {
        'category_slug': 'giperekstenzii',
        'name':        'Гиперэкстензия DFC SJ1005',
        'slug':        'product-192',
        'price':       7000,
        'image':       'images/products/H_192.jpg',
        'description': 'Гиперэкстензия DFC SJ1005',
        'is_hit': True,
        'order': 3,
    },
    {
        'category_slug': 'giperekstenzii',
        'name':        'Гиперэкстензия DFC SC-YW011',
        'slug':        'product-193',
        'price':       7500,
        'image':       'images/products/H_193.jpg',
        'description': 'Гиперэкстензия DFC SC-YW011',
        'is_hit': False,
        'order': 4,
    },
    {
        'category_slug': 'giperekstenzii',
        'name':        'Гиперэкстензия Optifit Avanta SX-51',
        'slug':        'product-194',
        'price':       9500,
        'image':       'images/products/H_194.jpg',
        'description': 'Технические характеристики:',
        'is_hit': False,
        'order': 5,
    },
    {
        'category_slug': 'giperekstenzii',
        'name':        'Складная гиперэкстензия (2in1) Optifit Catera SX55',
        'slug':        'product-195',
        'price':       12500,
        'image':       'images/products/H_195.jpg',
        'description': '',
        'is_hit': False,
        'order': 6,
    },
    {
        'category_slug': 'giperekstenzii',
        'name':        'Гиперэкстензия Winner/Oxygen Hyperpress Board',
        'slug':        'product-196',
        'price':       13500,
        'image':       'images/products/H_196.jpg',
        'description': 'Складная гиперэкстензия Winner (Oxygen) Hyperpress Board для тренировки мышц пресса и спины. Удобная подушка сидения толщиной 50 мм. позволяет комфортно тренироваться. Высокопрочная стальная рама с профилем 50*50 мм. выдерживает пользователя весом до 130 кг.',
        'is_hit': False,
        'order': 7,
    },
    {
        'category_slug': 'giperekstenzii',
        'name':        'Гиперэкстензия DFC Homegym SUB026',
        'slug':        'product-197',
        'price':       15500,
        'image':       'images/products/H_197.jpg',
        'description': 'Гиперэкстензия DFC Homegym SUB026',
        'is_hit': False,
        'order': 8,
    },
    {
        'category_slug': 'giperekstenzii',
        'name':        'Гиперэкстензия DFC Homegym SUB027',
        'slug':        'product-198',
        'price':       18000,
        'image':       'images/products/H_198.jpg',
        'description': 'Надежный тренажер для укрепления мышц живота, спины и бедер. Снижает усталость спины, увеличивает гибкость, улучшает кровообращение.',
        'is_hit': False,
        'order': 9,
    },
    {
        'category_slug': 'giperekstenzii',
        'name':        'DFC Z003',
        'slug':        'product-245',
        'price':       11000,
        'image':       'images/products/H_245.jpg',
        'description': 'Технические характеристики:',
        'is_hit': False,
        'order': 10,
    },
    {
        'category_slug': 'dsk-atlet',
        'name':        'Детский спортивный комплекс «ЮНЫЙ АТЛЕТ» модель «Эконом»',
        'slug':        'product-125',
        'price':       5500,
        'image':       'images/products/H_125.jpg',
        'description': '',
        'is_hit': True,
        'order': 1,
    },
    {
        'category_slug': 'dsk-atlet',
        'name':        'Детский спортивный комплекс «ЮНЫЙ АТЛЕТ» модель «Пристенный»',
        'slug':        'product-126',
        'price':       13000,
        'image':       'images/products/H_126.jpg',
        'description': 'Комплектация навесного оборудования:',
        'is_hit': False,
        'order': 2,
    },
    {
        'category_slug': 'dsk-atlet',
        'name':        'Детский спортивный комплекс «ЮНЫЙ АТЛЕТ» модель «Пол-потолок»',
        'slug':        'product-127',
        'price':       13500,
        'image':       'images/products/H_127.jpg',
        'description': '',
        'is_hit': True,
        'order': 3,
    },
    {
        'category_slug': 'dsk-atlet',
        'name':        'Детский спортивный комплекс «ЮНЫЙ АТЛЕТ» модель «Пол-потолок-Т»',
        'slug':        'product-128',
        'price':       14000,
        'image':       'images/products/H_128.jpg',
        'description': 'Комплектация навесного оборудования:',
        'is_hit': False,
        'order': 4,
    },
    {
        'category_slug': 'dsk-atlet',
        'name':        'Детский спортивный комплекс «АТЛЕТ»',
        'slug':        'product-153',
        'price':       14000,
        'image':       'images/products/H_153.jpg',
        'description': '',
        'is_hit': False,
        'order': 5,
    },
    {
        'category_slug': 'dsk-atlet',
        'name':        'Уличные детские качели Атлет',
        'slug':        'product-158',
        'price':       7500,
        'image':       'images/products/H_158.jpg',
        'description': 'труба стойки &#216; 42 мм',
        'is_hit': False,
        'order': 6,
    },
    {
        'category_slug': 'dsk-atlet',
        'name':        'Уличный детский спортивный комплекс Атлет',
        'slug':        'product-159',
        'price':       16000,
        'image':       'images/products/H_159.jpg',
        'description': 'Стойки: труба &#216; 42 мм;',
        'is_hit': False,
        'order': 7,
    },
    {
        'category_slug': 'dsk-atlet',
        'name':        'Детский спортивный комплекс «АТЛЕТ-Р»',
        'slug':        'product-167',
        'price':       11900,
        'image':       'images/products/H_167.jpg',
        'description': '',
        'is_hit': False,
        'order': 8,
    },
    {
        'category_slug': 'dsk-formula',
        'name':        'Гамма',
        'slug':        'product-174',
        'price':       12500,
        'image':       'images/products/H_174.jpg',
        'description': 'Тип установки - Пристенный, цвета в ассортименте',
        'is_hit': False,
        'order': 1,
    },
    {
        'category_slug': 'dsk-formula',
        'name':        'Забияка',
        'slug':        'product-175',
        'price':       10300,
        'image':       'images/products/H_175.jpg',
        'description': 'Тип установки - Пристенный, цвета в ассортименте',
        'is_hit': False,
        'order': 2,
    },
    {
        'category_slug': 'dsk-formula',
        'name':        'Лира',
        'slug':        'product-176',
        'price':       12500,
        'image':       'images/products/H_176.jpg',
        'description': 'Тип установки - Пристенный, цвета в ассортименте',
        'is_hit': False,
        'order': 3,
    },
    {
        'category_slug': 'dsk-formula',
        'name':        'Мечта',
        'slug':        'product-177',
        'price':       10700,
        'image':       'images/products/H_177.jpg',
        'description': 'Тип установки - Пристенный, цвета в ассортименте',
        'is_hit': False,
        'order': 4,
    },
    {
        'category_slug': 'dsk-formula',
        'name':        'Непоседа',
        'slug':        'product-178',
        'price':       10500,
        'image':       'images/products/H_178.jpg',
        'description': 'Тип установки - пристенный, цвета в ассортименте',
        'is_hit': False,
        'order': 5,
    },
    {
        'category_slug': 'dsk-formula',
        'name':        'Орленок',
        'slug':        'product-179',
        'price':       11600,
        'image':       'images/products/H_179.jpg',
        'description': 'Тип установки - пристенный, цвета в ассортименте',
        'is_hit': False,
        'order': 6,
    },
    {
        'category_slug': 'dsk-formula',
        'name':        'Сигма',
        'slug':        'product-180',
        'price':       11400,
        'image':       'images/products/H_180.jpg',
        'description': 'Тип установки - Пристенный, цвета в ассортименте',
        'is_hit': False,
        'order': 7,
    },
    {
        'category_slug': 'dsk-formula',
        'name':        'Стелла',
        'slug':        'product-181',
        'price':       11900,
        'image':       'images/products/H_181.jpg',
        'description': 'Тип установки - пристенный, цвета в ассортименте',
        'is_hit': False,
        'order': 8,
    },
    {
        'category_slug': 'dsk-formula',
        'name':        'Журавлик (угловой)',
        'slug':        'product-182',
        'price':       10100,
        'image':       'images/products/H_182.jpg',
        'description': 'Тип установки - Угловой | Пристенный, цвета в ассортименте',
        'is_hit': False,
        'order': 9,
    },
    {
        'category_slug': 'dsk-formula',
        'name':        'Робинзон',
        'slug':        'product-183',
        'price':       9700,
        'image':       'images/products/H_183.jpg',
        'description': 'Тип установки - Угловой | Пристенный, цвета в ассортименте',
        'is_hit': False,
        'order': 10,
    },
    {
        'category_slug': 'dsk-formula',
        'name':        'Карапуз',
        'slug':        'product-184',
        'price':       9900,
        'image':       'images/products/H_184.jpg',
        'description': 'Тип установки - пристенный, цвета в ассортименте',
        'is_hit': False,
        'order': 11,
    },
    {
        'category_slug': 'dsk-formula',
        'name':        'Аистенок',
        'slug':        'product-185',
        'price':       10500,
        'image':       'images/products/H_185.jpg',
        'description': 'Тип установки - пристенный, цвета в ассортименте',
        'is_hit': False,
        'order': 12,
    },
    {
        'category_slug': 'dsk-napolnye',
        'name':        'Игрунок',
        'slug':        'product-186',
        'price':       15500,
        'image':       'images/products/H_186.jpg',
        'description': 'Тип установки - напольный',
        'is_hit': True,
        'order': 1,
    },
    {
        'category_slug': 'dsk-napolnye',
        'name':        'Счастливчик',
        'slug':        'product-187',
        'price':       26500,
        'image':       'images/products/H_187.jpg',
        'description': '',
        'is_hit': False,
        'order': 2,
    },
    {
        'category_slug': 'dsk-napolnye',
        'name':        'Мурзилка',
        'slug':        'product-188',
        'price':       19500,
        'image':       'images/products/H_188.jpg',
        'description': '',
        'is_hit': False,
        'order': 3,
    },
    {
        'category_slug': 'dsk-napolnye',
        'name':        'Кубик',
        'slug':        'product-189',
        'price':       25000,
        'image':       'images/products/H_189.jpg',
        'description': 'Вес - 1 коробка: 30,1 кг | 2 коробка: 18,2 кг',
        'is_hit': False,
        'order': 4,
    },
    {
        'category_slug': 'dsk-napolnye',
        'name':        'Вершинка',
        'slug':        'product-190',
        'price':       21500,
        'image':       'images/products/H_190.jpg',
        'description': 'Вес - 1 коробка: 25,9 кг | 2 коробка: 11,7 кг',
        'is_hit': False,
        'order': 5,
    },
    {
        'category_slug': 'dsk-napolnye',
        'name':        'Артек',
        'slug':        'product-191',
        'price':       28500,
        'image':       'images/products/H_191.jpg',
        'description': '',
        'is_hit': False,
        'order': 6,
    },
    {
        'category_slug': 'dopolnitelnoe',
        'name':        'КОЛЬЦА ГИМНАСТИЧЕСКИЕ',
        'slug':        'product-131',
        'price':       700,
        'image':       'images/products/H_131.jpg',
        'description': 'Шнур ПМД трёхцветный - д. 10мм;',
        'is_hit': True,
        'order': 1,
    },
    {
        'category_slug': 'dopolnitelnoe',
        'name':        'КАНАТ ГИМНАСТИЧЕСКИЙ',
        'slug':        'product-132',
        'price':       1200,
        'image':       'images/products/H_132.jpg',
        'description': 'Материал – Х/Б; Диаметр каната – 28 мм; Длина – 2,0 метра. В комплект входят: - 1 катушка Допустимая нагрузка: до 100 кг.',
        'is_hit': False,
        'order': 2,
    },
    {
        'category_slug': 'dopolnitelnoe',
        'name':        'ВЕРЕВОЧНАЯ ЛЕСТНИЦА',
        'slug':        'product-133',
        'price':       1000,
        'image':       'images/products/H_133.jpg',
        'description': '',
        'is_hit': False,
        'order': 3,
    },
    {
        'category_slug': 'dopolnitelnoe',
        'name':        'КАЧЕЛИ',
        'slug':        'product-134',
        'price':       1200,
        'image':       'images/products/H_134.jpg',
        'description': '',
        'is_hit': False,
        'order': 4,
    },
    {
        'category_slug': 'dopolnitelnoe',
        'name':        'ТАРЗАНКА',
        'slug':        'product-135',
        'price':       600,
        'image':       'images/products/H_135.jpg',
        'description': '',
        'is_hit': False,
        'order': 5,
    },
    {
        'category_slug': 'dopolnitelnoe',
        'name':        'ТРАПЕЦИЯ',
        'slug':        'product-136',
        'price':       500,
        'image':       'images/products/H_136.jpg',
        'description': 'Шнур ПМД трехцветный – диаметр 10мм; Перекладина из твердых сортов дерева, лакированная.',
        'is_hit': False,
        'order': 6,
    },
    {
        'category_slug': 'dopolnitelnoe',
        'name':        'МАТ ГИМНАСТИЧЕСКИЙ 1,0Х0,5Х0,1 МЕТРА',
        'slug':        'product-139',
        'price':       2000,
        'image':       'images/products/H_139.jpg',
        'description': '',
        'is_hit': False,
        'order': 7,
    },
    {
        'category_slug': 'dopolnitelnoe',
        'name':        'МАТ ГИМНАСТИЧЕСКИЙ 1,0Х1,0Х0,1 МЕТРА',
        'slug':        'product-140',
        'price':       2700,
        'image':       'images/products/H_140.jpg',
        'description': '',
        'is_hit': False,
        'order': 8,
    },
    {
        'category_slug': 'dopolnitelnoe',
        'name':        'МАТ ГИМНАСТИЧЕСКИЙ 1,0Х1,0Х0,1 МЕТРА СКЛАДНОЙ',
        'slug':        'product-141',
        'price':       3000,
        'image':       'images/products/H_141.jpg',
        'description': '',
        'is_hit': False,
        'order': 9,
    },
    {
        'category_slug': 'dopolnitelnoe',
        'name':        'Стойка для гантелей FFS',
        'slug':        'product-142',
        'price':       9000,
        'image':       'images/products/H_142.jpg',
        'description': '',
        'is_hit': False,
        'order': 10,
    },
    {
        'category_slug': 'dopolnitelnoe',
        'name':        'Скамья для пресса Альфа',
        'slug':        'product-143',
        'price':       6500,
        'image':       'images/products/H_143.jpg',
        'description': '',
        'is_hit': False,
        'order': 11,
    },
    {
        'category_slug': 'dopolnitelnoe',
        'name':        'Подвес для груши FFS',
        'slug':        'product-145',
        'price':       3000,
        'image':       'images/products/H_145.jpg',
        'description': '',
        'is_hit': False,
        'order': 12,
    },
    {
        'category_slug': 'dopolnitelnoe',
        'name':        'Стойка для блинов FFS',
        'slug':        'product-151',
        'price':       6000,
        'image':       'images/products/H_151.jpg',
        'description': '',
        'is_hit': False,
        'order': 13,
    },
    {
        'category_slug': 'dopolnitelnoe',
        'name':        'ЛИАНА',
        'slug':        'product-157',
        'price':       1000,
        'image':       'images/products/H_157.jpg',
        'description': 'Шнур ПМД трехцветный – диаметр 10мм;',
        'is_hit': False,
        'order': 14,
    },
    {
        'category_slug': 'dopolnitelnoe',
        'name':        'КАНАТ ГИМНАСТИЧЕСКИЙ ПОЛИАМИД',
        'slug':        'product-160',
        'price':       1200,
        'image':       'images/products/H_160.jpg',
        'description': 'Материал – полиамид (пмд);Диаметр каната – 28 мм;Длина – 2,0 метра.В комплект входят:- 1 катушкаДопустимая нагрузка: до 100 кг.',
        'is_hit': False,
        'order': 15,
    },
    {
        'category_slug': 'dopolnitelnoe',
        'name':        'Стойка для гантелей FFS',
        'slug':        'product-244',
        'price':       8500,
        'image':       'images/products/H_244.jpg',
        'description': '',
        'is_hit': False,
        'order': 16,
    },
    {
        'category_slug': 'inversionnye-stoly',
        'name':        'DFC XJ-I-01A',
        'slug':        'product-246',
        'price':       14500,
        'image':       'images/products/H_246.jpg',
        'description': '',
        'is_hit': False,
        'order': 1,
    },
    {
        'category_slug': 'inversionnye-stoly',
        'name':        'DFC DFC I-12DL',
        'slug':        'product-247',
        'price':       16000,
        'image':       'images/products/H_247.jpg',
        'description': '',
        'is_hit': False,
        'order': 2,
    },
    {
        'category_slug': 'inversionnye-stoly',
        'name':        'Элит',
        'slug':        'product-248',
        'price':       19000,
        'image':       'images/products/H_248.jpg',
        'description': '',
        'is_hit': True,
        'order': 3,
    },
    {
        'category_slug': 'inversionnye-stoly',
        'name':        'Стандарт',
        'slug':        'product-254',
        'price':       14500,
        'image':       'images/products/H_254.jpg',
        'description': '',
        'is_hit': False,
        'order': 4,
    },
    {
        'category_slug': 'medboly',
        'name':        'Медбол 1',
        'slug':        'product-238',
        'price':       1600,
        'image':       'images/products/H_238.jpg',
        'description': '',
        'is_hit': False,
        'order': 1,
    },
    {
        'category_slug': 'medboly',
        'name':        'Медбол 2',
        'slug':        'product-239',
        'price':       1700,
        'image':       'images/products/H_239.jpg',
        'description': '',
        'is_hit': False,
        'order': 2,
    },
    {
        'category_slug': 'medboly',
        'name':        'Медбол 3',
        'slug':        'product-240',
        'price':       1800,
        'image':       'images/products/H_240.jpg',
        'description': '',
        'is_hit': False,
        'order': 3,
    },
    {
        'category_slug': 'medboly',
        'name':        'Медбол 4',
        'slug':        'product-241',
        'price':       2100,
        'image':       'images/products/H_241.jpg',
        'description': '',
        'is_hit': False,
        'order': 4,
    },
    {
        'category_slug': 'skami',
        'name':        'Силовая скамья со стойкой DFC TTF-307E',
        'slug':        'product-218',
        'price':       9600,
        'image':       'images/products/H_218.jpg',
        'description': 'Тренажер предназначен для домашнего использования.',
        'is_hit': False,
        'order': 1,
    },
    {
        'category_slug': 'skami',
        'name':        'Скамья под штангу DFC D210',
        'slug':        'product-219',
        'price':       9800,
        'image':       'images/products/H_219.jpg',
        'description': '',
        'is_hit': False,
        'order': 2,
    },
    {
        'category_slug': 'skami',
        'name':        'Скамья под штангу DFC D002',
        'slug':        'product-220',
        'price':       10700,
        'image':       'images/products/H_220.jpg',
        'description': '',
        'is_hit': False,
        'order': 3,
    },
    {
        'category_slug': 'skami',
        'name':        'Скамья под штангу DFC D-220',
        'slug':        'product-221',
        'price':       15200,
        'image':       'images/products/H_221.jpg',
        'description': '',
        'is_hit': False,
        'order': 4,
    },
    {
        'category_slug': 'skami',
        'name':        'Силовая скамья Weider 190TC',
        'slug':        'product-222',
        'price':       14500,
        'image':       'images/products/H_222.jpg',
        'description': 'Тип Скамья со стойками, многофункциональная',
        'is_hit': False,
        'order': 5,
    },
    {
        'category_slug': 'skami',
        'name':        'Скамья под штангу DFC D7828',
        'slug':        'product-223',
        'price':       19200,
        'image':       'images/products/H_223.jpg',
        'description': '',
        'is_hit': False,
        'order': 6,
    },
    {
        'category_slug': 'skami',
        'name':        'Скамья под штангу DFC D-730',
        'slug':        'product-224',
        'price':       20800,
        'image':       'images/products/H_224.jpg',
        'description': '',
        'is_hit': False,
        'order': 7,
    },
    {
        'category_slug': 'skami',
        'name':        'Скамья под штангу DFC D-3750',
        'slug':        'product-225',
        'price':       22400,
        'image':       'images/products/H_225.jpg',
        'description': '',
        'is_hit': False,
        'order': 8,
    },
    {
        'category_slug': 'skami',
        'name':        'Скамья под штангу DFC D-780',
        'slug':        'product-226',
        'price':       24000,
        'image':       'images/products/H_226.jpg',
        'description': '',
        'is_hit': False,
        'order': 9,
    },
    {
        'category_slug': 'skami',
        'name':        'Скамья под штангу WEIDER PRO 256',
        'slug':        'product-227',
        'price':       24000,
        'image':       'images/products/H_227.jpg',
        'description': 'Регулируемый угол наклона спинки.',
        'is_hit': False,
        'order': 10,
    },
    {
        'category_slug': 'sportivnye-kompleksy',
        'name':        'Спортивный комплекс Олимп',
        'slug':        'product-162',
        'price':       13500,
        'image':       'images/products/H_162.jpg',
        'description': 'Многофункциональный турник — 3 хвата турника: широкий, параллельный и обратно-параллельный.Складные брусья — просто поднимите упоры вверх и брусья станут незаметными. Дополнительные наклонные ручки разработаны специально для занятий на пресс.Мягкая опора для спины — полностью съемная опора поможет п',
        'is_hit': False,
        'order': 1,
    },
    {
        'category_slug': 'sportivnye-kompleksy',
        'name':        'Спортивный комплекс Старт',
        'slug':        'product-168',
        'price':       13500,
        'image':       'images/products/H_168.jpg',
        'description': 'Спортивный комплекс «Старт» с усиленным каркасом из профильной трубы.Многофункциональный турник — 3 хвата турника: широкий, узкий и параллельный. Регулируется по высоте.Складные брусья — просто поднимите упоры вверх и брусья станут незаметными. Дополнительные наклонные ручки разработаны специально д',
        'is_hit': False,
        'order': 2,
    },
    {
        'category_slug': 'sportivnye-kompleksy',
        'name':        'Многофункциональный силовой комплекс «Сталкер»',
        'slug':        'product-169',
        'price':       23000,
        'image':       'images/products/H_169.jpg',
        'description': 'Многофункциональный турник — 2 хвата турника: широкий и параллельный',
        'is_hit': False,
        'order': 3,
    },
    {
        'category_slug': 'sportivnye-kompleksy',
        'name':        'Спортивный комплекс Крафт',
        'slug':        'product-253',
        'price':       33000,
        'image':       'images/products/H_253.jpg',
        'description': '',
        'is_hit': False,
        'order': 4,
    },
    {
        'category_slug': 'sportivnye-kompleksy',
        'name':        'СК Торпеда',
        'slug':        'product-255',
        'price':       14000,
        'image':       'images/products/H_255.jpg',
        'description': '- турник, брусья, вертикальный пресс',
        'is_hit': False,
        'order': 5,
    },
    {
        'category_slug': 'stoyki',
        'name':        'Статика',
        'slug':        'product-172',
        'price':       15000,
        'image':       'images/products/H_172.jpg',
        'description': 'Стойка предназначена для таких упражнений, как подтягивания, отжимания, упражнения на пресс и многие другие.Турник многофункциональный с тремя хватами. Брусья для отжимания и пресса.',
        'is_hit': False,
        'order': 1,
    },
    {
        'category_slug': 'stoyki',
        'name':        'Спарта',
        'slug':        'product-173',
        'price':       11500,
        'image':       'images/products/H_173.jpg',
        'description': 'Максимальный вес пользователя 100 кг',
        'is_hit': False,
        'order': 2,
    },
    {
        'category_slug': 'turniki',
        'name':        'ТУРНИК АТЛЕТ «3 В 1»',
        'slug':        'product-137',
        'price':       5000,
        'image':       'images/products/H_137.jpg',
        'description': 'Цветовое исполнение: белый антик серебро, черный антик серебро Допустимая нагрузка, кг: 200 Вес изделия, кг: 12,5',
        'is_hit': True,
        'order': 1,
    },
    {
        'category_slug': 'turniki',
        'name':        'Турник трёххватный FFS',
        'slug':        'product-146',
        'price':       2500,
        'image':       'images/products/H_146.jpg',
        'description': 'способ установки - крепление к стене на 4 точки',
        'is_hit': False,
        'order': 2,
    },
    {
        'category_slug': 'turniki',
        'name':        'Турник настенный FFS',
        'slug':        'product-152',
        'price':       2500,
        'image':       'images/products/H_152.jpg',
        'description': 'способ установки: на 4 точки',
        'is_hit': False,
        'order': 3,
    },
    {
        'category_slug': 'turniki',
        'name':        'Турник настенный Атлет',
        'slug':        'product-156',
        'price':       2000,
        'image':       'images/products/H_156.jpg',
        'description': 'Способ установки: крепление к стене на 4 точки',
        'is_hit': False,
        'order': 4,
    },
    {
        'category_slug': 'turniki',
        'name':        'Турник+брусья Комбат',
        'slug':        'product-161',
        'price':       8800,
        'image':       'images/products/H_161.jpg',
        'description': 'Компактный и многофункциональный тренажер. Отлично подойдет для тренировок в домашних условиях',
        'is_hit': False,
        'order': 5,
    },
    {
        'category_slug': 'turniki',
        'name':        'Турник треххватный AC',
        'slug':        'product-166',
        'price':       3000,
        'image':       'images/products/H_166.jpg',
        'description': 'способ установки - крепление к стене на 6 точек',
        'is_hit': False,
        'order': 6,
    },
    {
        'category_slug': 'turniki',
        'name':        'Турник Титан-450-3',
        'slug':        'product-170',
        'price':       3000,
        'image':       'images/products/H_170.jpg',
        'description': 'Ширина турника 950 мм',
        'is_hit': False,
        'order': 7,
    },
    {
        'category_slug': 'turniki',
        'name':        'Турник-перекладина',
        'slug':        'product-171',
        'price':       1500,
        'image':       'images/products/H_171.jpg',
        'description': 'Тип установки-раздвижной',
        'is_hit': False,
        'order': 8,
    },
    {
        'category_slug': 'shvedskie-stenki',
        'name':        'Шведская стенка+турник/брусья FFS',
        'slug':        'product-147',
        'price':       11800,
        'image':       'images/products/H_147.jpg',
        'description': 'Турник/брусья съемные',
        'is_hit': True,
        'order': 1,
    },
    {
        'category_slug': 'shvedskie-stenki',
        'name':        'Шведская стенка серии Атлет',
        'slug':        'product-154',
        'price':       8500,
        'image':       'images/products/H_154.jpg',
        'description': 'Стойки лестницы: выполнены из трубы 40х40 мм',
        'is_hit': False,
        'order': 2,
    },
    {
        'category_slug': 'shvedskie-stenki',
        'name':        'Шведская стенка+турник/брусья Атлет',
        'slug':        'product-155',
        'price':       10000,
        'image':       'images/products/H_155.jpg',
        'description': 'Способ установки: навесной,',
        'is_hit': False,
        'order': 3,
    },
]


# ---------------------------------------------------------------------------
# Kyrgyz auto-translation dictionary (sorted longest-first at runtime)
# ---------------------------------------------------------------------------
_KG = {
    # Compound phrases first (to avoid partial replacements)
    'Шведская стенка+турник/брусья': 'Швед дубалы+горизонталдык кубур/брустар',
    'Шведские стенки+турник/брусья': 'Швед дубалдары+горизонталдык кубур/брустар',
    'Детский спортивный комплекс':   'Балдар спорттук комплекси',
    'Многофункциональный силовой комплекс': 'Көп функциялуу күч комплекси',
    'Многофункциональный турник':    'Көп функциялуу горизонталдык кубур',
    'Спортивный комплекс':           'Спорттук комплекс',
    'Уличный детский спортивный комплекс': 'Сырткы балдар спорттук комплекси',
    'Уличные детские качели':        'Сырткы балдар качелеси',
    'Детские качели':                'Балдар качелеси',
    'Силовая скамья со стойкой':     'Стойкалуу күч скамейкасы',
    'Скамья под штангу':             'Штанга скамейкасы',
    'Скамья для пресса':             'Пресс скамейкасы',
    'Силовая скамья':                'Күч скамейкасы',
    'Подвес для груши':              'Коңгуроо илгичи',
    'Стойка для гантелей':           'Гантель стойкасы',
    'Стойка для блинов':             'Блин стойкасы',
    'Боксерский мешок детский':      'Балдар боксердук баштыгы',
    'Боксерский мешок':              'Боксердук баштык',
    'Ремешок для прокачки шеи':      'Моюн машыктыруу курлугу',
    'Подушка настенная для бокса':   'Бокс үчүн дубалдагы жаздык',
    'Чучело борцовское':             'Күрөш кукласы',
    'Борцовское чучело':             'Күрөш кукласы',
    'Веревочная лестница':           'Жип баскыч',
    'Канат гимнастический':          'Гимнастикалык жип',
    'КАНАТ ГИМНАСТИЧЕСКИЙ':          'ГИМНАСТИКАЛЫК ЖИП',
    'ВЕРЕВОЧНАЯ ЛЕСТНИЦА':           'ЖИП БАСКЫЧ',
    'Инверсионный стол':             'Инверсиялык стол',
    'ИНВЕРСИОННЫЙ СТОЛ':             'ИНВЕРСИЯЛЫК СТОЛ',
    'Беговая дорожка':               'Жүгүрүү дорожкасы',
    'Беговые дорожки':               'Жүгүрүү дорожкалары',
    'Складная гиперэкстензия':       'Бүктөлүүчү гиперэкстензия',
    'Гиперэкстензия':                'Гиперэкстензия',
    'БРУСЬЯ ОТКИДНЫЕ СО СПИНКОЙ ДЛЯ ДСК СЕРИИ': 'ДСК СЕРИЯСЫ ҮЧҮН АРТКЫ ЖАКТАГЫ БҮКТӨЛМӨ БРУСТАР',
    'КОЛЬЦА ГИМНАСТИЧЕСКИЕ':         'ГИМНАСТИКАЛЫК ШАКЕКЧЕЛЕР',
    'МАТ ГИМНАСТИЧЕСКИЙ':            'ГИМНАСТИКАЛЫК МАТ',
    'КАНАТ ГИМНАСТИЧЕСКИЙ ПОЛИАМИД': 'ПОЛИАМИД ГИМНАСТИКАЛЫК ЖИП',
    'ТУРНИК АТЛЕТ':                  'АТЛЕТ ГОРИЗОНТАЛДЫК КУБУРУ',
    'Турник-перекладина':            'Горизонталдык кубур',
    'Турник настенный':              'Дубалдагы горизонталдык кубур',
    'Турник трёххватный':            'Үч кармалгычтуу горизонталдык кубур',
    'Турник треххватный':            'Үч кармалгычтуу горизонталдык кубур',
    'Турник+брусья':                 'Горизонталдык кубур+брустар',
    'Турник':                        'Горизонталдык кубур',
    'Брусья навесные':               'Илинмелүү брустар',
    'Брусья складные':               'Бүктөлүүчү брустар',
    'Брусья':                        'Брустар',
    'Шведская стенка':               'Швед дубалы',
    'Шведские стенки':               'Швед дубалдары',
    'ШВЕДСКАЯ СТЕНКА':               'ШВЕД ДУБАЛЫ',
    'Мат гимнастический':            'Гимнастикалык мат',
    'Кольца гимнастические':         'Гимнастикалык шакекчелер',
    'Силуэт большой':                'Чоң силуэт',
    'Силуэт малый':                  'Кичи силуэт',
    'Форма груши':                   'Коңгуроо формасы',
    'Фитбол':                        'Фитбол',
    'Медбол':                        'Медбол',
    'МЕДБОЛ':                        'МЕДБОЛ',
    'Лиана':                         'Лиана',
    'ЛИАНА':                         'ЛИАНА',
    'ТАРЗАНКА':                      'ТАРЗАНКА',
    'ТРАПЕЦИЯ':                      'ТРАПЕЦИЯ',
    'КАЧЕЛИ':                        'КАЧЕЛЕСИ',
    'Трапеция':                      'Трапеция',
    'Тарзанка':                      'Тарзанка',
    'Качели':                        'Качелеси',
    'Многофункциональный':           'Көп функциялуу',
    'Складной':                      'Бүктөлүүчү',
    'Складная':                      'Бүктөлүүчү',
    'Складные':                      'Бүктөлүүчү',
    'Силовой':                       'Күч',
    'Напольный':                     'Жердеги',
    'Настенный':                     'Дубалдагы',
    'Настенная':                     'Дубалдагы',
    'Пристенный':                    'Дубалдагы',
    'Откидные':                      'Бүктөлмө',
    'Навесные':                      'Илинмелүү',
    'Уличный':                       'Сырткы',
    'Детский':                       'Балдар',
    'Детские':                       'Балдар',
    # Descriptions
    'Допустимая нагрузка':           'Уруксат берилген жүктөмө',
    'Максимальный вес пользователя': 'Колдонуучунун максималдуу салмагы',
    'Максимальный вес':              'Максималдуу салмак',
    'Характеристики':                'Мүнөздөмөлөр',
    'Технические характеристики':    'Техникалык мүнөздөмөлөр',
    'В комплект входят':             'Комплектке кирет',
    'В комплекте':                   'Комплектте',
    'Регулируемый угол наклона':     'Жөнгө салынуучу ийилүү бурчу',
    'Регулируемый':                  'Жөнгө салынуучу',
    'Регулируемая высота':           'Жөнгө салынуучу бийиктик',
    'крепление к стене':             'дубалга бекитүү',
    'Крепление':                     'Бекитме',
    'способ установки':              'орнотуу ыкмасы',
    'Способ установки':              'Орнотуу ыкмасы',
    'Тип установки':                 'Орнотуу түрү',
    'Тип Скамья':                    'Скамейка түрү',
    'Цветовое исполнение':           'Түс жасалмасы',
    'Вес изделия':                   'Буюмдун салмагы',
    'Порошковая покраска':           'Порошоктук боёо',
    'Нагрузка до':                   'Жүктөмө чейин',
    'Нагрузка':                      'Жүктөмө',
    'Высота':                        'Бийиктик',
    'высота':                        'бийиктик',
    'Ширина':                        'Туурасы',
    'ширина турника':                'горизонталдык кубурдун туурасы',
    'Длина':                         'Узундугу',
    'Диаметр':                       'Диаметри',
    'диаметр':                       'диаметри',
    'Материал':                      'Материал',
    'раздвижной':                    'сыдырмалуу',
    'навесной':                      'илинмелүү',
    'домашних условиях':             'үй шартында',
    'домашнего использования':       'үйдө колдонуу үчүн',
    'для тренировки':                'машыгуу үчүн',
    'для занятий':                   'машыгуу үчүн',
    'мышц спины':                    'арка булчуңдары',
    'мышц пресса':                   'пресс булчуңдары',
    'мышц живота':                   'карын булчуңдары',
    'металлообработке':              'металл иштетүүдө',
    'Профессиональный':              'Профессионалдык',
    'профессиональный':              'профессионалдык',
    'Компактный':                    'Компакт',
    'Надежный':                      'Ишенимдүү',
    'надежный':                      'ишенимдүү',
    'Стойка предназначена':          'Стойка арналган',
    'предназначен для':              'үчүн арналган',
}

import re as _re

def kg_translate(text):
    if not text:
        return ''
    result = text
    for ru, kg in sorted(_KG.items(), key=lambda x: len(x[0]), reverse=True):
        result = result.replace(ru, kg)
    return result


class Command(BaseCommand):
    help = 'Загружает начальные данные в базу данных'

    def handle(self, *args, **kwargs):
        self.stdout.write('Очищаю старые данные...')
        Product.objects.all().delete()
        Category.objects.all().delete()

        self.stdout.write('Создаю категории...')
        cat_map = {}
        for slug, name, emoji, order in CATEGORIES:
            cat = Category.objects.create(slug=slug, name=name, emoji=emoji, order=order)
            cat_map[slug] = cat

        self.stdout.write('Создаю товары...')
        for data in PRODUCTS:
            cat_slug = data.pop('category_slug')
            data['name_kg'] = kg_translate(data.get('name', ''))
            data['description_kg'] = kg_translate(data.get('description', ''))
            Product.objects.create(category=cat_map[cat_slug], **data)

        self.stdout.write(self.style.SUCCESS(
            f'Готово! Создано {len(CATEGORIES)} категорий и {len(PRODUCTS)} товаров.'
        ))
