# Generated by Django 6.0.5 on 2026-05-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_kg',
            field=models.TextField(blank=True, verbose_name='Описание (кырг.)'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_kg',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название (кырг.)'),
        ),
    ]
