# Generated by Django 6.0.5 on 2026-05-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_description_kg_product_name_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_kg',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название (кырг.)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название (рус.)'),
        ),
    ]
